package com.corestack.khidmatai.ui.theme

import androidx.compose.runtime.compositionLocalOf

data class AppStrings(
    // Onboarding
    val onboardingTitle: String,
    val onboardingDesc: String,
    val onboardingBtnLocation: String,
    val onboardingPrivacy: String,
    val onboardingSkip: String,
    // Home
    val homeGreeting: String,
    val homePrompt: String,
    val homeSearchHint: String,
    val homeChangeLocation: String,
    val homeUrgencyTitle: String,
    val homeQuickChipsTitle: String,
    val homeBtnFindService: String,
    val homeBtnFindEmergency: String,
    val homeProcessing: String,
    val homeClear: String,
    // Urgency
    val urgencyLow: String,
    val urgencyMedium: String,
    val urgencyHigh: String,
    val urgencyEmergency: String,
    // Quick chips
    val quickAc: String,
    val quickAcQuery: String,
    val quickPlumber: String,
    val quickPlumberQuery: String,
    val quickElectrician: String,
    val quickElectricianQuery: String,
    val quickTutor: String,
    val quickTutorQuery: String,
    val quickBeautician: String,
    val quickBeauticianQuery: String,
    val quickCarpenter: String,
    val quickCarpenterQuery: String,
    // Emergency Banner
    val emergencyModeTitle: String,
    val emergencyModeDesc: String,
    // Processing
    val processingTitle: String,
    val processingEmergencyTitle: String,
    val processingDesc: String,
    // Result Success
    val resultSuccessEmergency: String,
    val resultSuccessTitle: String,
    val resultSuccessAiDecision: String,
    val resultSuccessAiReasoningFallback: String,
    val resultSuccessCallNow: String,
    val resultSuccessWhatsapp: String,
    val resultSuccessMapView: String,
    val resultSuccessAppointmentDetails: String,
    val resultSuccessNextSteps: String,
    val resultSuccessViewDetails: String,
    val resultSuccessBackHome: String,
    // Result Unavailable
    val resultUnavailTitle: String,
    val resultUnavailDesc: String,
    val resultUnavailWhatHappened: String,
    val resultUnavailWhatHappenedDesc: String,
    val resultUnavailSuggestion: String,
    val resultUnavailSuggestionDesc: String,
    val resultUnavailBtnRetry: String,
    val resultUnavailBtnDifferent: String,
    // Bookings
    val bookingsTitle: String,
    val bookingsFilterAll: String,
    val bookingsFilterUpcoming: String,
    val bookingsFilterCompleted: String,
    val bookingsEmptyTitle: String,
    val bookingsEmptyDesc: String,
    val bookingsEmptyBtn: String,
    // Booking Detail
    val bookingDetailTitle: String,
    val bookingDetailNotFound: String,
    val bookingDetailGoBack: String,
    val bookingDetailConfirmed: String,
    val bookingDetailFollowupInfo: String,
    val bookingDetailReminderYes: String,
    val bookingDetailReminderNo: String,
    val bookingDetailAiDecision: String,
    val bookingDetailAppointmentDetails: String,
    val bookingDetailNextSteps: String,
    val bookingDetailAgentLog: String,
    val bookingDetailStatusConfirmed: String,
    // Nav
    val navHome: String,
    val navBookings: String,
    val navProfile: String,
    // Badges
    val badgeCompleted: String,
    val badgePending: String,
    val badgeFailed: String,
    val badgeUpcoming: String,
    val badgeEmergency: String,
    // Voice
    val voiceTitle: String,
    val voiceSubtitle: String,
    val voiceBtnCancel: String,
    val voiceBtnStop: String,
    val voiceTranscribing: String,
    // Notifications
    val notifAppName: String,
    val notifMessage: String,
    val notifTime: String,
    // Profile
    val profileTitle: String,
    val profileSignOut: String,
    val profileNotifications: String,
    val profileLanguage: String,
    val profileSavedLocations: String,
    val profilePrivacy: String,
    val profileAbout: String,
    val profileBookings: String,
    val profileRating: String,
    val profileVerified: String,
    // Trace stages
    val traceIntent: String,
    val traceLlm: String,
    val traceService: String,
    val traceUrgency: String,
    val traceDiscovery: String,
    val traceRanking: String,
    val traceSelection: String,
    val traceExecution: String,
    val traceFollowup: String,
    // Location Picker
    val locationPickerTitle: String,
    val locationPickerSearchHint: String,
    val locationPickerDetect: String,
    val locationPickerDetecting: String,
    val locationPickerPopularAreas: String,
    val locationPickerMajorCities: String,
    val locationPickerNoResults: String,
    // Onboarding permission states
    val onboardingDetectingLocation: String,
    val onboardingPermissionDenied: String,
    val locationPermissionRequired: String,
)

val EnglishStrings = AppStrings(
    onboardingTitle = "First, tell us your location",
    onboardingDesc = "So we can find the best service providers near you",
    onboardingBtnLocation = "📍 Allow Location Access",
    onboardingPrivacy = "Only used for service matching.\nNo data will be shared.",
    onboardingSkip = "Skip for now",
    homeGreeting = "Hello!",
    homePrompt = "What do you need today?",
    homeSearchHint = "Write your requirement...",
    homeChangeLocation = "Change",
    homeUrgencyTitle = "How urgent is it?",
    homeQuickChipsTitle = "Quick Needs?",
    homeBtnFindService = "Find Service →",
    homeBtnFindEmergency = "Find Emergency Service 🚨",
    homeProcessing = "Processing...",
    homeClear = "Clear ✕",
    urgencyLow = "🟢 Low",
    urgencyMedium = "🟡 Medium",
    urgencyHigh = "🔴 High",
    urgencyEmergency = "🚨 Emergency",
    quickAc = "❄️ AC Tech",
    quickAcQuery = "I need an AC technician",
    quickPlumber = "🔧 Plumber",
    quickPlumberQuery = "I need a plumber, pipe is leaking",
    quickElectrician = "⚡ Electrician",
    quickElectricianQuery = "There is an electrical issue, need an electrician",
    quickTutor = "📚 Tutor",
    quickTutorQuery = "Need a math tutor for my kid",
    quickBeautician = "💅 Beautician",
    quickBeauticianQuery = "I need a beautician at home",
    quickCarpenter = "🪚 Carpenter",
    quickCarpenterQuery = "Need a carpenter for furniture repair",
    emergencyModeTitle = "Emergency Mode Active",
    emergencyModeDesc = "Use only for genuine emergencies.",
    processingTitle = "Agent is running...",
    processingEmergencyTitle = "Emergency Request — Priority Processing 🚨",
    processingDesc = "AI is orchestrating your request",
    resultSuccessEmergency = "EMERGENCY BOOKING",
    resultSuccessTitle = "Booking Confirmed!",
    resultSuccessAiDecision = "🤖 Why selected? (AI Decision)",
    resultSuccessAiReasoningFallback = "AI selected the best provider.",
    resultSuccessCallNow = "📞 Call Now",
    resultSuccessWhatsapp = "💬 WhatsApp",
    resultSuccessMapView = "📍 Map View",
    resultSuccessAppointmentDetails = "📅 Appointment Details",
    resultSuccessNextSteps = "Next Steps",
    resultSuccessViewDetails = "View Full Booking Details",
    resultSuccessBackHome = "Back to Home",
    resultUnavailTitle = "No Provider Available",
    resultUnavailDesc = "Service is not available in this area right now.",
    resultUnavailWhatHappened = "What happened?",
    resultUnavailWhatHappenedDesc = "No verified provider found.",
    resultUnavailSuggestion = "Suggestion:",
    resultUnavailSuggestionDesc = "Try again after some time.",
    resultUnavailBtnRetry = "🔄 Retry Request",
    resultUnavailBtnDifferent = "Try Different Service",
    bookingsTitle = "My Bookings",
    bookingsFilterAll = "All",
    bookingsFilterUpcoming = "Upcoming",
    bookingsFilterCompleted = "Completed",
    bookingsEmptyTitle = "No bookings yet",
    bookingsEmptyDesc = "Book your first service!",
    bookingsEmptyBtn = "Find a Service",
    bookingDetailTitle = "Booking Detail",
    bookingDetailNotFound = "Booking not found",
    bookingDetailGoBack = "Go Back",
    bookingDetailConfirmed = "Confirmed",
    bookingDetailFollowupInfo = "🔔 Follow-up Info",
    bookingDetailReminderYes = "Reminder set: ✅ Yes",
    bookingDetailReminderNo = "Reminder set: ❌ No",
    bookingDetailAiDecision = "🤖 Why selected? (AI Decision)",
    bookingDetailAppointmentDetails = "📅 Appointment Details",
    bookingDetailNextSteps = "Next Steps",
    bookingDetailAgentLog = "🤖 AI Agent Log",
    bookingDetailStatusConfirmed = "Status: Booking Confirmed",
    navHome = "Home",
    navBookings = "Bookings",
    navProfile = "Profile",
    badgeCompleted = "Completed",
    badgePending = "Pending",
    badgeFailed = "Failed",
    badgeUpcoming = "Upcoming",
    badgeEmergency = "Emergency",
    voiceTitle = "Speak your request...",
    voiceSubtitle = "Speak in Urdu or English",
    voiceBtnCancel = "✕ Cancel",
    voiceBtnStop = "⏹ Stop & Use",
    voiceTranscribing = "Transcribing...",
    notifAppName = "KaamKaro",
    notifMessage = "⏰ Reminder: Your AC service is in 1 hour. Kamran Khan is on the way.",
    notifTime = "09:30 AM",
    profileTitle = "Profile",
    profileSignOut = "Sign Out",
    profileNotifications = "Notifications",
    profileLanguage = "Language",
    profileSavedLocations = "Saved Locations",
    profilePrivacy = "Privacy",
    profileAbout = "About KhidmatAI",
    profileBookings = "Bookings",
    profileRating = "My Rating",
    profileVerified = "Verified",
    traceIntent = "Understanding request",
    traceLlm = "AI analysis",
    traceService = "Identifying service",
    traceUrgency = "Setting urgency level",
    traceDiscovery = "Discovering providers",
    traceRanking = "Selecting best match",
    traceSelection = "Selecting provider",
    traceExecution = "Confirming booking",
    traceFollowup = "Setting reminders",
    locationPickerTitle = "Select Location",
    locationPickerSearchHint = "Search locations...",
    locationPickerDetect = "Detect My Location",
    locationPickerDetecting = "Detecting...",
    locationPickerPopularAreas = "Popular Areas",
    locationPickerMajorCities = "Major Cities",
    locationPickerNoResults = "No results found",
    onboardingDetectingLocation = "Getting your location...",
    onboardingPermissionDenied = "Location permission denied. Please enable in Settings.",
    locationPermissionRequired = "Grant Location Permission",
)

val UrduStrings = AppStrings(
    onboardingTitle = "پہلے اپنی لوکیشن بتائیں",
    onboardingDesc = "تاکہ ہم آپ کے قریب کے بہترین سروس پرووائیڈرز تلاش کر سکیں",
    onboardingBtnLocation = "📍 لوکیشن استعمال کرنے کی اجازت دیں",
    onboardingPrivacy = "صرف سروس میچنگ کے لیے استعمال ہوگی۔\nکوئی ڈیٹا شیئر نہیں کیا جائے گا۔",
    onboardingSkip = "ابھی کے لیے چھوڑ دیں",
    homeGreeting = "السلام علیکم!",
    homePrompt = "آج کیا چاہیے آپ کو؟",
    homeSearchHint = "اپنی ضرورت لکھیں...",
    homeChangeLocation = "تبدیل کریں",
    homeUrgencyTitle = "کتنی ضرورت ہے؟",
    homeQuickChipsTitle = "کیا چاہیے؟",
    homeBtnFindService = "سروس تلاش کریں ←",
    homeBtnFindEmergency = "ایمرجنسی سروس تلاش کریں 🚨",
    homeProcessing = "پروسیسنگ...",
    homeClear = "صاف کریں ✕",
    urgencyLow = "🟢 کم",
    urgencyMedium = "🟡 درمیانی",
    urgencyHigh = "🔴 زیادہ",
    urgencyEmergency = "🚨 ایمرجنسی",
    quickAc = "❄️ اے سی ٹیکنیشن",
    quickAcQuery = "مجھے اے سی ٹیکنیشن چاہیے",
    quickPlumber = "🔧 پلمبر",
    quickPlumberQuery = "مجھے پلمبر چاہیے، پائپ لیک ہے",
    quickElectrician = "⚡ الیکٹریشن",
    quickElectricianQuery = "بجلی کا مسئلہ ہے، الیکٹریشن چاہیے",
    quickTutor = "📚 ٹیوٹر",
    quickTutorQuery = "بچے کے لیے ریاضی کا ٹیوٹر چاہیے",
    quickBeautician = "💅 بیوٹیشن",
    quickBeauticianQuery = "گھر پر بیوٹیشن چاہیے",
    quickCarpenter = "🪚 بڑھئی",
    quickCarpenterQuery = "فرنیچر ٹھیک کرنے کے لیے بڑھئی چاہیے",
    emergencyModeTitle = "ایمرجنسی موڈ ایکٹو",
    emergencyModeDesc = "صرف حقیقی ایمرجنسی کے لیے استعمال کریں۔",
    processingTitle = "ایجنٹ کام کر رہا ہے...",
    processingEmergencyTitle = "ایمرجنسی درخواست — فوری پروسیسنگ 🚨",
    processingDesc = "AI آپ کی درخواست پر کام کر رہا ہے",
    resultSuccessEmergency = "ایمرجنسی بکنگ",
    resultSuccessTitle = "بکنگ کنفرم ہو گئی!",
    resultSuccessAiDecision = "🤖 کیوں چنا؟ (AI فیصلہ)",
    resultSuccessAiReasoningFallback = "AI نے بہترین پرووائیڈر کا انتخاب کیا۔",
    resultSuccessCallNow = "📞 ابھی کال کریں",
    resultSuccessWhatsapp = "💬 واٹس ایپ",
    resultSuccessMapView = "📍 نقشہ دیکھیں",
    resultSuccessAppointmentDetails = "📅 اپوائنٹمنٹ کی تفصیلات",
    resultSuccessNextSteps = "اگلے اقدامات",
    resultSuccessViewDetails = "بکنگ کی مکمل تفصیلات دیکھیں",
    resultSuccessBackHome = "ہوم پر واپس جائیں",
    resultUnavailTitle = "کوئی پرووائیڈر دستیاب نہیں",
    resultUnavailDesc = "فی الحال اس علاقے میں سروس دستیاب نہیں ہے۔",
    resultUnavailWhatHappened = "کیا ہوا؟",
    resultUnavailWhatHappenedDesc = "کوئی تصدیق شدہ پرووائیڈر نہیں ملا۔",
    resultUnavailSuggestion = "مشورہ:",
    resultUnavailSuggestionDesc = "کچھ دیر بعد دوبارہ کوشش کریں۔",
    resultUnavailBtnRetry = "🔄 دوبارہ کوشش کریں",
    resultUnavailBtnDifferent = "مختلف سروس کے لیے کوشش کریں",
    bookingsTitle = "میری بکنگز",
    bookingsFilterAll = "تمام",
    bookingsFilterUpcoming = "آنے والی",
    bookingsFilterCompleted = "مکمل",
    bookingsEmptyTitle = "ابھی تک کوئی بکنگ نہیں",
    bookingsEmptyDesc = "اپنی پہلی سروس بک کریں!",
    bookingsEmptyBtn = "سروس تلاش کریں",
    bookingDetailTitle = "بکنگ کی تفصیلات",
    bookingDetailNotFound = "بکنگ نہیں ملی",
    bookingDetailGoBack = "واپس جائیں",
    bookingDetailConfirmed = "کنفرم ہو گئی",
    bookingDetailFollowupInfo = "🔔 فالو اپ کی معلومات",
    bookingDetailReminderYes = "ریمائنڈر سیٹ: ✅ ہاں",
    bookingDetailReminderNo = "ریمائنڈر سیٹ: ❌ نہیں",
    bookingDetailAiDecision = "🤖 کیوں چنا؟ (AI فیصلہ)",
    bookingDetailAppointmentDetails = "📅 اپوائنٹمنٹ کی تفصیلات",
    bookingDetailNextSteps = "اگلے اقدامات",
    bookingDetailAgentLog = "🤖 AI ایجنٹ کی لاگ",
    bookingDetailStatusConfirmed = "سٹیٹس: بکنگ کنفرم ہو گئی",
    navHome = "ہوم",
    navBookings = "بکنگز",
    navProfile = "پروفائل",
    badgeCompleted = "مکمل",
    badgePending = "جاری ہے",
    badgeFailed = "ناکام",
    badgeUpcoming = "آنے والی",
    badgeEmergency = "ایمرجنسی",
    voiceTitle = "بول کر بتائیں...",
    voiceSubtitle = "اردو یا انگریزی میں بولیں",
    voiceBtnCancel = "✕ منسوخ کریں",
    voiceBtnStop = "⏹ رکیں اور استعمال کریں",
    voiceTranscribing = "ٹرانسکرائب ہو رہا ہے...",
    notifAppName = "کام کرو",
    notifMessage = "⏰ یاد دہانی: آپ کی AC سروس 1 گھنٹے میں ہے۔ کامران خان آ رہا ہے۔",
    notifTime = "09:30 AM",
    profileTitle = "پروفائل",
    profileSignOut = "سائن آؤٹ",
    profileNotifications = "اطلاعات",
    profileLanguage = "زبان",
    profileSavedLocations = "محفوظ لوکیشنز",
    profilePrivacy = "پرائیویسی",
    profileAbout = "KhidmatAI کے بارے میں",
    profileBookings = "بکنگز",
    profileRating = "میری ریٹنگ",
    profileVerified = "تصدیق شدہ",
    traceIntent = "آپ کی درخواست سمجھی جا رہی ہے",
    traceLlm = "AI تجزیہ",
    traceService = "سروس کی شناخت",
    traceUrgency = "ارجنسی لیول کا تعین",
    traceDiscovery = "پرووائیڈرز کی تلاش",
    traceRanking = "بہترین کا انتخاب",
    traceSelection = "پرووائیڈر کو منتخب کیا",
    traceExecution = "بکنگ کنفرم کی",
    traceFollowup = "ریمائنڈر سیٹ کیے",
    locationPickerTitle = "لوکیشن منتخب کریں",
    locationPickerSearchHint = "لوکیشن تلاش کریں...",
    locationPickerDetect = "میری لوکیشن معلوم کریں",
    locationPickerDetecting = "معلوم ہو رہی ہے...",
    locationPickerPopularAreas = "مشہور علاقے",
    locationPickerMajorCities = "بڑے شہر",
    locationPickerNoResults = "کوئی نتیجہ نہیں ملا",
    onboardingDetectingLocation = "آپ کی لوکیشن معلوم ہو رہی ہے...",
    onboardingPermissionDenied = "لوکیشن کی اجازت نہیں ملی۔ سیٹنگز میں جا کر فعال کریں۔",
    locationPermissionRequired = "لوکیشن کی اجازت دیں",
)

val LocalAppStrings = compositionLocalOf { EnglishStrings }
